# Use the Nginx image
FROM nginx:alpine
# Copy the default Nginx configuration file (optional)
COPY nginx.conf /etc/nginx/conf.d/default.conf 
COPY dist /usr/share/nginx/html
# Expose port 80
EXPOSE 80
